SELECT DISTINCT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    TRUNCATE(C.DAILY_FEE * 30 * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    (SELECT CAR_TYPE, DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상'
    ) P ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE 
            H.CAR_ID = C.CAR_ID 
            AND NOT (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30')
    )
    AND TRUNCATE(C.DAILY_FEE * 30 * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100, 0) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE, 
    C.CAR_ID DESC;
