SELECT DISTINCT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
INNER JOIN 
    (SELECT CAR_TYPE, DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상'
    ) P ON C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    AND (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID IS NULL
    AND TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE, 
    C.CAR_ID DESC;