SELECT DISTINCT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    (SELECT CAR_TYPE, DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상'
    ) P ON C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    AND (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID IS NULL
    AND TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE, 
    C.CAR_ID DESC;








     
     
# # SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, 
# # CASE 
# #     WHEN A.CAR_TYPE ='세단'
# #     THEN ROUND(30*A.DAILY_FEE*0.9)
# #     WHEN A.CAR_TYPE ='SUV'
# #     THEN ROUND(30*A.DAILY_FEE*0.92)
# # END AS FEE
# # FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
# # INNER JOIN (CAR_RENTAL_COMPANY_CAR A
# #     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# #     ON A.CAR_TYPE = C.CAR_TYPE)
# # ON A.CAR_ID = B.CAR_ID
# # WHERE A.CAR_TYPE IN ('세단','SUV')
# #     AND DATE_FORMAT(B.START_DATE, '%Y-%m-%d') <= '2022-11-01' 
# #     AND DATE_FORMAT(B.END_DATE, '%Y-%m-%d') >= '2022-11-30' AND
# #     CASE 
# #         WHEN A.CAR_TYPE ='세단'
# #         THEN 30*A.DAILY_FEE*0.9 >= 500000
# #             AND 30*A.DAILY_FEE*0.9 < 2000000
# #         WHEN A.CAR_TYPE ='SUV'
# #         THEN 30*A.DAILY_FEE*0.92 >= 500000
# #             AND 30*A.DAILY_FEE*0.92 < 2000000
# #     END
# # ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
# select *
# from car_rental_company_rental_history
# where month(end_date)=9 and day(end_date)=7